### ISSUE TITLE
API to 'Upload Data Pre-Annotated' is not working

### ISSUE THREAD

**Issue by obai-d** [DataTurks/DataTurks#12]
Looking at the documentation for [Upload Data Pre-Annotated](https://docs.dataturks.com/?version=latest#6b6514db-bd53-f2a3-b317-a32e1016ceb2) and [Upload Data](https://docs.dataturks.com/?version=latest#3621207b-e284-cbec-0bc9-ac89bc9d4c29), I don't see any difference in the way both the API calls are made. Perhaps something is missing in the documentation for `Upload Data Pre-Annotated`?

Upload file goes through, but the UI shows the whole JSON as is.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/52337213/68355510-822d4a00-00dd-11ea-932e-0fc17762a486.png">

**Comment by fahimsun** [comment]
I am facing same issue what's the solution?

**Comment by obai-d** [comment]
@fahimsun for pre-annotated, use the following params `?format=PRE_TAGGED_JSON&itemStatus=preTagged`
